/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 castle.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/castle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Castle.geometry} material={nodes.Castle.material} position={[81.686, 4.556, -3.946]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[5.556, 5.556, 6.3]} />
      <mesh geometry={nodes.Lines023.geometry} material={nodes.Lines023.material} />
    </group>
  )
}

useGLTF.preload('/castle.glb')
