/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 level.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/level.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lines005.geometry} material={nodes.Lines005.material} position={[-0.174, 0, 0]} />
      <mesh geometry={nodes.Lines006.geometry} material={nodes.Lines006.material} />
      <mesh geometry={nodes.Lines007.geometry} material={nodes.Lines007.material} />
      <mesh geometry={nodes.Lines008.geometry} material={nodes.Lines008.material} position={[0, 0, -5.498]} />
      <mesh geometry={nodes.pillar001.geometry} material={nodes.pillar001.material} position={[19.66, -1.03, -0.97]} scale={[0.625, 0.312, 0.625]} />
      <mesh geometry={nodes.pillar002.geometry} material={nodes.pillar002.material} position={[19.66, -1.03, -6.468]} scale={[0.625, 0.312, 0.625]} />
      <mesh geometry={nodes.stairs.geometry} material={nodes.stairs.material} position={[18.179, 1.255, -3.676]} rotation={[0, -Math.PI / 2, 0]} scale={[2.5, 0.237, 0.237]} />
      <mesh geometry={nodes.wall001.geometry} material={nodes.wall001.material} position={[18.97, 0.135, -3.878]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[4.14, 3.52, 2.763]} />
      <mesh geometry={nodes.Lines009.geometry} material={nodes.Lines009.material} position={[63.132, 0, -7.429]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Lines010.geometry} material={nodes.Lines010.material} position={[25.013, 0.024, 0.085]} />
      <mesh geometry={nodes.Lines011.geometry} material={nodes.Lines011.material} position={[62.959, 0, -7.429]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Lines012.geometry} material={nodes.Lines012.material} position={[62.959, 0, -1.93]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.pillar003.geometry} material={nodes.pillar003.material} position={[43.299, -1.03, -6.459]} rotation={[Math.PI, 0, Math.PI]} scale={[0.625, 0.312, 0.625]} />
      <mesh geometry={nodes.pillar004.geometry} material={nodes.pillar004.material} position={[43.299, -1.03, -0.961]} rotation={[Math.PI, 0, Math.PI]} scale={[0.625, 0.312, 0.625]} />
      <mesh geometry={nodes.stairs001.geometry} material={nodes.stairs001.material} position={[44.78, 1.255, -3.753]} rotation={[0, Math.PI / 2, 0]} scale={[2.5, 0.237, 0.237]} />
      <mesh geometry={nodes.Lines001.geometry} material={nodes.Lines001.material} position={[3.696, -2.278, -0.027]} scale={[1.412, 1.75, 1.406]} />
      <mesh geometry={nodes.Tower001.geometry} material={nodes.Tower001.material} position={[-6.374, 2.542, 0.161]} rotation={[Math.PI / 2, 0, 0]} scale={[3.065, 3.053, 3.8]} />
      <mesh geometry={nodes.floor1.geometry} material={nodes.floor1.material} position={[5.963, 0.91, -3.788]} rotation={[0, 0, -Math.PI]} scale={[-12.419, -0.139, -3.876]} />
      <mesh geometry={nodes.Lines002.geometry} material={nodes.Lines002.material} position={[0, -0.154, 0]} />
      <mesh geometry={nodes.Lines018.geometry} material={nodes.Lines018.material} position={[53.478, -0.154, 0]} scale={[1.399, 1, 1]} />
      <mesh geometry={nodes.floor1002.geometry} material={nodes.floor1002.material} position={[61.821, 0.91, -3.788]} rotation={[0, 0, -Math.PI]} scale={[-17.376, -0.139, -3.876]} />
      <mesh geometry={nodes.wall.geometry} material={nodes.wall.material} position={[-4.04, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines.geometry} material={nodes.Lines.material} />
      <mesh geometry={nodes.Wall1.geometry} material={nodes.Wall1.material} position={[-4.04, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines019.geometry} material={nodes.Lines019.material} position={[50.917, 0, 0]} />
      <mesh geometry={nodes.Wall1010.geometry} material={nodes.Wall1010.material} position={[46.877, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines004.geometry} material={nodes.Lines004.material} position={[0, 0, -7.795]} />
      <mesh geometry={nodes.Wall1009.geometry} material={nodes.Wall1009.material} position={[15.981, 0, -7.795]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines020.geometry} material={nodes.Lines020.material} position={[50.924, 0, -7.795]} />
      <mesh geometry={nodes.Wall1019.geometry} material={nodes.Wall1019.material} position={[66.905, 0, -7.795]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Wall1020.geometry} material={nodes.Wall1020.material} position={[71.891, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines021.geometry} material={nodes.Lines021.material} />
      <mesh geometry={nodes.Wall1021.geometry} material={nodes.Wall1021.material} position={[71.891, 0, -7.792]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines022.geometry} material={nodes.Lines022.material} position={[0, 0, -7.792]} />
      <mesh geometry={nodes.Lines013.geometry} material={nodes.Lines013.material} position={[25.831, 1.576, -0.845]} scale={[0.937, 1, 0.755]} />
      <mesh geometry={nodes.floor1001.geometry} material={nodes.floor1001.material} position={[31.418, 2.639, -3.706]} rotation={[0, 0, -Math.PI]} scale={[-11.635, -0.139, -2.927]} />
      <mesh geometry={nodes.pillar005.geometry} material={nodes.pillar005.material} position={[26.419, -0.964, -0.821]} rotation={[Math.PI, 0, Math.PI]} scale={[0.438, 0.219, 0.438]} />
      <mesh geometry={nodes.pillar006.geometry} material={nodes.pillar006.material} position={[26.419, -0.964, -6.588]} rotation={[Math.PI, 0, Math.PI]} scale={[0.438, 0.219, 0.438]} />
      <mesh geometry={nodes.Lines014.geometry} material={nodes.Lines014.material} position={[40.206, -0.242, -1.501]} rotation={[Math.PI, 0, Math.PI]} scale={0.701} />
      <mesh geometry={nodes.Lines015.geometry} material={nodes.Lines015.material} position={[40.206, -0.242, -7.268]} rotation={[Math.PI, 0, Math.PI]} scale={0.701} />
      <mesh geometry={nodes.pillar007.geometry} material={nodes.pillar007.material} position={[35.7, -0.964, -6.588]} rotation={[Math.PI, 0, Math.PI]} scale={[0.438, 0.219, 0.438]} />
      <mesh geometry={nodes.pillar008.geometry} material={nodes.pillar008.material} position={[35.7, -0.964, -0.821]} rotation={[Math.PI, 0, Math.PI]} scale={[0.438, 0.219, 0.438]} />
      <mesh geometry={nodes.Lines016.geometry} material={nodes.Lines016.material} position={[49.487, -0.242, -7.268]} rotation={[Math.PI, 0, Math.PI]} scale={0.701} />
      <mesh geometry={nodes.Lines017.geometry} material={nodes.Lines017.material} position={[49.487, -0.242, -1.501]} rotation={[Math.PI, 0, Math.PI]} scale={0.701} />
      <mesh geometry={nodes.pillar025.geometry} material={nodes.pillar025.material} position={[31.515, 3.758, -6.608]} rotation={[0, Math.PI / 2, 0]} scale={[0.01, 0.01, 11.672]} />
      <mesh geometry={nodes.pillar009.geometry} material={nodes.pillar009.material} position={[31.515, 3.758, -0.782]} rotation={[0, Math.PI / 2, 0]} scale={[0.01, 0.01, 11.672]} />
      <mesh geometry={nodes.Castle.geometry} material={nodes.Castle.material} position={[81.686, 4.556, -3.946]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[5.556, 5.556, 6.3]} />
      <mesh geometry={nodes.Lines023.geometry} material={nodes.Lines023.material} />
    </group>
  )
}

useGLTF.preload('/level.glb')
