/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mario.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import marioSrc from './mario.glb'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(marioSrc)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="mario" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="button1" geometry={nodes.button1.geometry} material={materials.buttonMaterial} skeleton={nodes.button1.skeleton} />
          <skinnedMesh name="button1001" geometry={nodes.button1001.geometry} material={materials.buttonMaterial} skeleton={nodes.button1001.skeleton} />
          <skinnedMesh name="cap" geometry={nodes.cap.geometry} material={materials.shirt} skeleton={nodes.cap.skeleton} />
          <skinnedMesh name="Eyes" geometry={nodes.Eyes.geometry} material={materials.eyeswhite} skeleton={nodes.Eyes.skeleton} />
          <skinnedMesh name="Eyes001" geometry={nodes.Eyes001.geometry} material={materials.eyeswhite} skeleton={nodes.Eyes001.skeleton} />
          <skinnedMesh name="Eyes002" geometry={nodes.Eyes002.geometry} material={materials.pupil} skeleton={nodes.Eyes002.skeleton} />
          <skinnedMesh name="Eyes003" geometry={nodes.Eyes003.geometry} material={materials.pupil} skeleton={nodes.Eyes003.skeleton} />
          <skinnedMesh name="face1" geometry={nodes.face1.geometry} material={materials.skin} skeleton={nodes.face1.skeleton} />
          <skinnedMesh name="glove1" geometry={nodes.glove1.geometry} material={materials.gloves} skeleton={nodes.glove1.skeleton} />
          <skinnedMesh name="glove1001" geometry={nodes.glove1001.geometry} material={materials.gloves} skeleton={nodes.glove1001.skeleton} />
          <skinnedMesh name="glove1002" geometry={nodes.glove1002.geometry} material={materials.gloves} skeleton={nodes.glove1002.skeleton} />
          <skinnedMesh name="glove1003" geometry={nodes.glove1003.geometry} material={materials.gloves} skeleton={nodes.glove1003.skeleton} />
          <skinnedMesh name="hair" geometry={nodes.hair.geometry} material={materials.moustache} skeleton={nodes.hair.skeleton} />
          <skinnedMesh name="hand1" geometry={nodes.hand1.geometry} material={materials.shirt} skeleton={nodes.hand1.skeleton} />
          <skinnedMesh name="hand1001" geometry={nodes.hand1001.geometry} material={materials.shirt} skeleton={nodes.hand1001.skeleton} />
          <skinnedMesh name="leg1002" geometry={nodes.leg1002.geometry} material={materials.blueshirt} skeleton={nodes.leg1002.skeleton} />
          <skinnedMesh name="leg1003" geometry={nodes.leg1003.geometry} material={materials.blueshirt} skeleton={nodes.leg1003.skeleton} />
          <skinnedMesh name="Lines001" geometry={nodes.Lines001.geometry} material={materials.line} skeleton={nodes.Lines001.skeleton} />
          <skinnedMesh name="moustache" geometry={nodes.moustache.geometry} material={materials.moustache} skeleton={nodes.moustache.skeleton} />
          <skinnedMesh name="neck" geometry={nodes.neck.geometry} material={materials.skin} skeleton={nodes.neck.skeleton} />
          <skinnedMesh name="shirt1" geometry={nodes.shirt1.geometry} material={materials.blueshirt} skeleton={nodes.shirt1.skeleton} />
          <skinnedMesh name="shoe1" geometry={nodes.shoe1.geometry} material={materials.shoes} skeleton={nodes.shoe1.skeleton} />
          <skinnedMesh name="shoe1001" geometry={nodes.shoe1001.geometry} material={materials.shoes} skeleton={nodes.shoe1001.skeleton} />
          <skinnedMesh name="stomach" geometry={nodes.stomach.geometry} material={materials.shirt} skeleton={nodes.stomach.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(marioSrc)
