/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stairs1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stairs1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lines005.geometry} material={nodes.Lines005.material} position={[-0.174, 0, 0]} />
      <mesh geometry={nodes.Lines006.geometry} material={nodes.Lines006.material} />
      <mesh geometry={nodes.Lines007.geometry} material={nodes.Lines007.material} />
      <mesh geometry={nodes.Lines008.geometry} material={nodes.Lines008.material} position={[0, 0, -5.498]} />
      <mesh geometry={nodes.pillar001.geometry} material={nodes.pillar001.material} position={[19.66, -1.03, -0.97]} scale={[0.625, 0.312, 0.625]} />
      <mesh geometry={nodes.pillar002.geometry} material={nodes.pillar002.material} position={[19.66, -1.03, -6.468]} scale={[0.625, 0.312, 0.625]} />
      <mesh geometry={nodes.stairs.geometry} material={nodes.stairs.material} position={[18.179, 1.255, -3.676]} rotation={[0, -Math.PI / 2, 0]} scale={[2.5, 0.237, 0.237]} />
      <mesh geometry={nodes.wall001.geometry} material={nodes.wall001.material} position={[18.97, 0.135, -3.878]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[4.14, 3.52, 2.763]} />
    </group>
  )
}

useGLTF.preload('/stairs1.glb')
