/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stairs2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stairs2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lines009.geometry} material={nodes.Lines009.material} position={[63.132, 0, -7.429]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Lines010.geometry} material={nodes.Lines010.material} position={[25.013, 0.024, 0.085]} />
      <mesh geometry={nodes.Lines011.geometry} material={nodes.Lines011.material} position={[62.959, 0, -7.429]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Lines012.geometry} material={nodes.Lines012.material} position={[62.959, 0, -1.93]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.pillar003.geometry} material={nodes.pillar003.material} position={[43.299, -1.03, -6.459]} rotation={[Math.PI, 0, Math.PI]} scale={[0.625, 0.312, 0.625]} />
      <mesh geometry={nodes.pillar004.geometry} material={nodes.pillar004.material} position={[43.299, -1.03, -0.961]} rotation={[Math.PI, 0, Math.PI]} scale={[0.625, 0.312, 0.625]} />
      <mesh geometry={nodes.stairs001.geometry} material={nodes.stairs001.material} position={[44.78, 1.255, -3.753]} rotation={[0, Math.PI / 2, 0]} scale={[2.5, 0.237, 0.237]} />
      <mesh geometry={nodes.wall002.geometry} material={nodes.wall002.material} position={[18.97, 0.135, -3.878]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[4.14, 3.52, 2.763]} />
    </group>
  )
}

useGLTF.preload('/stairs2.glb')
