/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 towers.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/towers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lines001.geometry} material={nodes.Lines001.material} position={[3.696, -2.278, -0.027]} scale={[1.412, 1.75, 1.406]} />
      <mesh geometry={nodes.Tower001.geometry} material={nodes.Tower001.material} position={[-6.374, 2.542, 0.161]} rotation={[Math.PI / 2, 0, 0]} scale={[3.065, 3.053, 3.8]} />
    </group>
  )
}

useGLTF.preload('/towers.glb')
