/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 walls2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/walls2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lines018.geometry} material={nodes.Lines018.material} position={[53.478, -0.154, 0]} scale={[1.399, 1, 1]} />
      <mesh geometry={nodes.floor1002.geometry} material={nodes.floor1002.material} position={[61.821, 0.91, -3.788]} rotation={[0, 0, -Math.PI]} scale={[-17.376, -0.139, -3.876]} />
      <mesh geometry={nodes.Lines019.geometry} material={nodes.Lines019.material} position={[50.917, 0, 0]} />
      <mesh geometry={nodes.Wall1010.geometry} material={nodes.Wall1010.material} position={[46.877, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines020.geometry} material={nodes.Lines020.material} position={[50.924, 0, -7.795]} />
      <mesh geometry={nodes.Wall1019.geometry} material={nodes.Wall1019.material} position={[66.905, 0, -7.795]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Wall1020.geometry} material={nodes.Wall1020.material} position={[71.891, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines021.geometry} material={nodes.Lines021.material} />
      <mesh geometry={nodes.Wall1021.geometry} material={nodes.Wall1021.material} position={[71.891, 0, -7.792]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines022.geometry} material={nodes.Lines022.material} position={[0, 0, -7.792]} />
    </group>
  )
}

useGLTF.preload('/walls2.glb')
