/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 walls1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/walls1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor1.geometry} material={nodes.floor1.material} position={[5.963, 0.91, -3.788]} rotation={[0, 0, -Math.PI]} scale={[-12.419, -0.139, -3.876]} />
      <mesh geometry={nodes.Lines002.geometry} material={nodes.Lines002.material} position={[0, -0.154, 0]} />
      <mesh geometry={nodes.Lines.geometry} material={nodes.Lines.material} />
      <mesh geometry={nodes.Wall1.geometry} material={nodes.Wall1.material} position={[-4.04, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
      <mesh geometry={nodes.Lines004.geometry} material={nodes.Lines004.material} position={[0, 0, -7.795]} />
      <mesh geometry={nodes.Wall1009.geometry} material={nodes.Wall1009.material} position={[15.981, 0, -7.795]} rotation={[Math.PI / 2, 0, 0]} scale={2.522} />
    </group>
  )
}

useGLTF.preload('/walls1.glb')
